name: "GitHub OIDC AWS"
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  oidc-test:
    runs-on: ubuntu-latest     
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: us-east-1
      - name: Test AWS credentials again
        run: aws sts get-caller-identity
